import { useEffect, useState } from 'react'
import { SectorsPieChart, StateDataChart, TimeTrend } from '@/components/dashboard'
import Head from 'next/head'

export default function Home() {

  const [badgeData, setBadgeData] = useState<Array<string>>([])
  const [societyData, setSocietyData] = useState<SocietyDataOverYears[]>([])
  const [sectors, setSectors] = useState<Array<SectorsData>>([])
  const [stateData, setStateData] = useState<Array<StateData>>([])
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    const fetchHomePageData = async () => {
      setLoading(true)

      const res = await fetch('http://localhost:3000/api/home')
      const data = await res.json()
      const { badgeData, sectors, societyData, stateData } = data

      setBadgeData(badgeData)
      setSectors(sectors)
      setSocietyData(societyData)
      setStateData(stateData)

      setLoading(false)
    }
    fetchHomePageData()
  }, [])

  return (
    <>
      <Head>
        <title>CRCS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mx-4 text-gray-700'>

        {loading ?
          <img className='h-20 w-70 mx-auto rounded-full' src='https://miro.medium.com/v2/resize:fit:1400/1*CsJ05WEGfunYMLGfsT2sXA.gif' alt='loader' />
          :
          <div className=''>

            {/* badge data  */}
            <div className='flex space-x-10 p-1 ml-72'>
              {badgeData?.map((item: any, index) => (
                <div key={index}
                  className={`${index % 2 === 0 ? 'bg-red-100' : 'bg-blue-100'} p-2 w-40 shadow-sm shadow-gray-400 text-center rounded-xl`}
                >
                  <p className='text-3xl font-bold'>{item.value}</p>
                  <p className='text-md mt-1 font-semibold'>{item.title}</p>
                </div>
              ))}
            </div>

            <div className='flex space-x-20 items-start h-60 my-7'>
              {/* sectors pie chart */}
              <div className='border-r border-gray-300'>
                <SectorsPieChart sectors={sectors} />
              </div>
              {/* society registration trend over time */}
              <TimeTrend societyData={societyData} />
            </div>
            {/* sector distribution  */}
            {/* <div className=''>
                <div className='rounded-3xl shadow-lg shadow-gray-400 mb-3'>
                  <h2 className='font-bold text-xl py-3 text-center mt-2'>Sectors Distribution</h2>
                  <p className='text-sm border-b text-center -mt-3 pb-2 border-gray-400'>(Scroll to see more)</p>
                  <div className='h-48 overflow-x-hidden overflow-y-scroll mb-2'>
                    {sectors.map((item: any, index) => (
                      <div key={index} className=' flex hover:bg-gray-200 pb-2 hover:cursor-pointer justify-between p-3 border-b space-x-20 border-gray-100'>
                        <p className='font-semibold'>{item.sector}</p>
                        <p className='font-bold text-lg'>{item.percentage}%</p>
                      </div>
                    )
                    )}
                  </div>
                </div>
              </div> */}


            <div className='mt-14 p-10'>
              <StateDataChart stateData={stateData} />
            </div>
          </div>
        }
      </div>
    </>
  )
}
